FROM golang:1.10-alpine

ENV PORT 8080
EXPOSE 8080

RUN apk update && \
        apk add git

ENV appDir /go/src/github.com/jbelmont/api-workshop

RUN mkdir -p ${appDir}
WORKDIR ${appDir}

COPY . ${appDir}

RUN go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/githubnemo/CompileDaemon && \
    dep ensure

CMD CompileDaemon -log-prefix=false -build="go build ./cmd/apid/" -command="./apid"
